In [1]:
from bs4 import BeautifulSoup
from requests import get
import pandas as pd

In [2]:
url='https://www.imdb.com/search/title/?release_date=2017&sort=num_votes,desc&page=1'
response=get(url)

In [3]:
html_soup=BeautifulSoup(response.text,'html.parser')

In [4]:
movie_containers=html_soup.find_all('div',class_='lister-item mode-advanced')
print(type(movie_containers))
print(len(movie_containers))

<class 'bs4.element.ResultSet'>
50

In [40]:
first_movie

<div class="lister-item mode-advanced">
<div class="lister-top-right">
<div class="ribbonize" data-caller="filmosearch" data-tconst="tt3315342"></div>
</div>
<div class="lister-item-image float-left">
<a href="/title/tt3315342/"> <img alt="Logan" class="loadlate" data-tconst="tt3315342" height="98" loadlate="https://m.media-amazon.com/images/M/MV5BYzc5MTU4N2EtYTkyMi00NjdhLTg3NWEtMTY4OTEyMzJhZTAzXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX67_CR0,0,67,98_AL_.jpg" src="https://m.media-amazon.com/images/G/01/imdb/images/nopicture/large/film-184890147._CB466725069_.png" width="67"/>
</a> </div>
<div class="lister-item-content">
<h3 class="lister-item-header">
<span class="lister-item-index unbold text-primary">1.</span>
<a href="/title/tt3315342/">Logan</a>
<span class="lister-item-year text-muted unbold">(2017)</span>
</h3>
<p class="text-muted">
<span class="certificate">R</span>
<span class="ghost">|</span>
<span class="runtime">137 min</span>
<span class="ghost">|</span>
<span class="genre">
Action, Drama, Sci-Fi            </span>
</p>
<div class="ratings-bar">
<div class="inline-block ratings-imdb-rating" data-value="8.1" name="ir">
<span class="global-sprite rating-star imdb-rating"></span>
<strong>8.1</strong>
</div>
<div class="inline-block ratings-user-rating">
<span class="userRatingValue" data-tconst="tt3315342" id="urv_tt3315342">
<span class="global-sprite rating-star no-rating"></span>
<span class="rate" data-no-rating="Rate this" data-value="0" name="ur">Rate this</span>
</span>
<div class="starBarWidget" id="sb_tt3315342">
<div class="rating rating-list" data-auth="" data-ga-identifier="" data-starbar-class="rating-list" data-user="" id="tt3315342|imdb|8.1|8.1|adv_li_tt||advsearch|title" itemprop="aggregateRating" itemscope="" itemtype="http://schema.org/AggregateRating" title="Users rated this 8.1/10 (606,946 votes) - click stars to rate">
<meta content="8.1" itemprop="ratingValue"/>
<meta content="10" itemprop="bestRating"/>
<meta content="606946" itemprop="ratingCount"/>
<span class="rating-bg"> </span>
<span class="rating-imdb" style="width: 113.4px"> </span>
<span class="rating-stars">
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>1</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>2</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>3</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>4</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>5</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>6</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>7</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>8</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>9</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>10</span></a>
</span>
<span class="rating-rating"><span class="value">8.1</span><span class="grey">/</span><span class="grey">10</span></span>
<span class="rating-cancel"><a href="/title/tt3315342/vote?v=X;k=" rel="nofollow" title="Delete"><span>X</span></a></span>
 </div>
</div>
</div>
<div class="inline-block ratings-metascore">
<span class="metascore favorable">77        </span>
        Metascore
            </div>
</div>
<p class="text-muted">
    In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety.</p>
<p class="">
    Director:
<a href="/name/nm0003506/">James Mangold</a>
<span class="ghost">|</span>
    Stars:
<a href="/name/nm0413168/">Hugh Jackman</a>,
<a href="/name/nm0001772/">Patrick Stewart</a>,
<a href="/name/nm6748436/">Dafne Keen</a>,
<a href="/name/nm2933542/">Boyd Holbrook</a>
</p>
<p class="sort-num_votes-visible">
<span class="text-muted">Votes:</span>
<span data-value="606946" name="nv">606,946</span>
<span class="ghost">|</span> <span class="text-muted">Gross:</span>
<span data-value="226,277,068" name="nv">$226.28M</span>
</p>
</div>
</div>

In [20]:
first_movie=movie_containers[0]

In [39]:
first_name=first_movie.h3.a.text
first_name

'Logan'

In [45]:
first_rating=first_movie.strong.text
first_rating

'8.1'

In [49]:
first_year=first_movie.find('span',class_='lister-item-year text-muted unbold').text
first_year

'(2017)'

In [66]:
first_vote=first_movie.find('span',attrs={'name':'nv'})
first_vote=int(first_vote['data-value'])
first_vote

606946

In [70]:
first_metascore=first_movie.find('span',class_="metascore favorable").text
first_metascore=int(first_metascore)
first_metascore

77

In [98]:
Names=[]
Ratings=[]
Votes=[]
Years=[]
Metascores=[]

for container in movie_containers:  
    if container.find('div', class_ = 'ratings-metascore') is not None:
# The name
        Name=container.h3.a.text
        Names.append(Name)
    
        Year=container.find('span',class_='lister-item-year').text
        Years.append(Year)
    
        Rating=float(container.strong.text)
        Ratings.append(Rating)
    
        Vote=container.find('span',attrs={'name':'nv'})
        Vote=int(Vote['data-value'])
        Votes.append(Vote)
        
        m_score = container.find('span', class_ = 'metascore').text
        Metascores.append(int(m_score))

In [100]:
df=pd.DataFrame({'Name':Names,'Ratings':Ratings,'Vote':Votes,"MetaScore":Metascores,'Year':Year})

In [101]:
df

,Name,Ratings,Vote,MetaScore,Year
0,Logan,8.1,606946,77,(2017)
1,Thor: Ragnarok,7.9,540562,74,(2017)
2,Guardians of the Galaxy Vol. 2,7.6,530649,67,(2017)
3,Star Wars: Episode VIII - The Last Jedi,7.0,530433,85,(2017)
4,Wonder Woman,7.4,522016,76,(2017)
5,Dunkirk,7.9,508761,94,(2017)
6,Spider-Man: Homecoming,7.4,476768,73,(2017)
7,Get Out,7.7,451536,85,(2017)
8,It,7.3,427069,69,(2017)
9,Blade Runner 2049,8.0,421294,81,(2017)
10,Baby Driver,7.6,403737,86,(2017)
11,"Three Billboards Outside Ebbing, Missouri",8.2,390157,88,(2017)
12,Justice League,6.4,357696,45,(2017)
13,The Shape of Water,7.3,343551,87,(2017)
14,John Wick: Chapter 2,7.5,337209,75,(2017)
15,Coco,8.4,328719,81,(2017)
16,Jumanji: Welcome to the Jungle,6.9,294067,58,(2017)
17,Beauty and the Beast,7.1,256131,65,(2017)
18,Kong: Skull Island,6.6,255042,62,(2017)
19,Kingsman: The Golden Circle,6.7,252676,44,(2017)
20,Pirates of the Caribbean: Dead Men Tell No Tales,6.6,245552,39,(2017)
21,Alien: Covenant,6.4,241413,65,(2017)
22,The Greatest Showman,7.6,216961,48,(2017)
23,War for the Planet of the Apes,7.4,215386,82,(2017)
24,Lady Bird,7.4,210309,94,(2017)
25,Murder on the Orient Express,6.5,195231,52,(2017)
26,Life,6.6,195063,54,(2017)
27,The Fate of the Furious,6.7,193563,56,(2017)
28,Ghost in the Shell,6.3,187408,52,(2017)
29,Wind River,7.7,186644,73,(2017)
30,Call Me by Your Name,7.9,183470,93,(2017)
31,King Arthur: Legend of the Sword,6.7,180984,41,(2017)
32,Mother!,6.6,176503,75,(2017)
33,The Hitman's Bodyguard,6.9,175457,47,(2017)
34,The Mummy,5.4,164938,34,(2017)
35,Atomic Blonde,6.7,164397,63,(2017)
36,"I, Tonya",7.5,163777,77,(2017)
37,Bright,6.3,159258,29,(2017)
38,Darkest Hour,7.4,156214,75,(2017)
39,Valerian and the City of a Thousand Planets,6.5,152776,51,(2017)
40,Baywatch,5.5,150903,37,(2017)
41,American Made,7.1,147184,65,(2017)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 5 columns):
Name         42 non-null object
Ratings      42 non-null float64
Vote         42 non-null int64
MetaScore    42 non-null int64
Year         42 non-null object
dtypes: float64(1), int64(2), object(2)
memory usage: 1.8+ KB